server:
  port: 8080
javax:
  sql:
    DataSource:
      helloDataSource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        dataSource:
          url: jdbc:postgresql://localhost:5432/hello
          user: postgres
          password: postgres